FQN_MAIN  = "BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_INSUMOS"
FQN_COR   = "BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_CORRECOES"
FQN_APR   = "BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_APROVADOS"
FQN_RMV   = "BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_REMOVIDOS"

FQN_USERS = "BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_USERS"
FQN_LOG_VALID  = 'BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_LOG_VALIDACAO'
FQN_LOG_REPROV = 'BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_LOG_REPROVACAO'
FQN_LOG_RMV    = 'BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_LOG_REMOVIDOS'

FQN_LOG_ATUAL  = 'BASES_SPDO.DB_APP_CATALOGO.TB_CATALOGO_LOG_ATUALIZACAO'
